# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AccountsScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountsScreen(object):
    def setupUi(self, AccountsScreen):
        AccountsScreen.setObjectName("AccountsScreen")
        AccountsScreen.resize(760, 580)
        self.centralwidget = QtWidgets.QWidget(AccountsScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(20, 20, 121, 51))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(20, 80, 121, 51))
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(20, 140, 121, 51))
        self.button3.setObjectName("button3")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(20, 200, 121, 51))
        self.button4.setObjectName("button4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 20, 141, 16))
        self.label.setObjectName("label")
        AccountsScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AccountsScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        AccountsScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AccountsScreen)
        self.statusbar.setObjectName("statusbar")
        AccountsScreen.setStatusBar(self.statusbar)

        self.retranslateUi(AccountsScreen)
        QtCore.QMetaObject.connectSlotsByName(AccountsScreen)

    def retranslateUi(self, AccountsScreen):
        _translate = QtCore.QCoreApplication.translate
        AccountsScreen.setWindowTitle(_translate("AccountsScreen", "MainWindow"))
        self.button1.setText(_translate("AccountsScreen", "Tasks"))
        self.button2.setText(_translate("AccountsScreen", "Profile"))
        self.button3.setText(_translate("AccountsScreen", "Settings"))
        self.button4.setText(_translate("AccountsScreen", "Accounts"))
        self.label.setText(_translate("AccountsScreen", "Accounts Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AccountsScreen = QtWidgets.QMainWindow()
    ui = Ui_AccountsScreen()
    ui.setupUi(AccountsScreen)
    AccountsScreen.show()
    sys.exit(app.exec_())
