# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProfileScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileScreen(object):
    def setupUi(self, ProfileScreen):
        ProfileScreen.setObjectName("ProfileScreen")
        ProfileScreen.resize(760, 580)
        self.centralwidget = QtWidgets.QWidget(ProfileScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(20, 20, 121, 51))
        self.button1.setObjectName("button1")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(20, 140, 121, 51))
        self.button3.setObjectName("button3")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(20, 80, 121, 51))
        self.button2.setObjectName("button2")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(20, 200, 121, 51))
        self.button4.setObjectName("button4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 40, 47, 13))
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(220, 60, 131, 21))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(220, 90, 131, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(220, 120, 131, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(220, 210, 131, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(220, 180, 131, 21))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(220, 150, 131, 21))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        ProfileScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProfileScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        ProfileScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProfileScreen)
        self.statusbar.setObjectName("statusbar")
        ProfileScreen.setStatusBar(self.statusbar)

        self.retranslateUi(ProfileScreen)
        QtCore.QMetaObject.connectSlotsByName(ProfileScreen)

    def retranslateUi(self, ProfileScreen):
        _translate = QtCore.QCoreApplication.translate
        ProfileScreen.setWindowTitle(_translate("ProfileScreen", "MainWindow"))
        self.button1.setText(_translate("ProfileScreen", "Tasks"))
        self.button3.setText(_translate("ProfileScreen", "Settings"))
        self.button2.setText(_translate("ProfileScreen", "Profile"))
        self.button4.setText(_translate("ProfileScreen", "Accounts"))
        self.label.setText(_translate("ProfileScreen", "Billing"))
        self.label_2.setText(_translate("ProfileScreen", "TextLabel"))
        self.label_3.setText(_translate("ProfileScreen", "Profile Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileScreen = QtWidgets.QMainWindow()
    ui = Ui_ProfileScreen()
    ui.setupUi(ProfileScreen)
    ProfileScreen.show()
    sys.exit(app.exec_())
