# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsScreen(object):
    def setupUi(self, SettingsScreen):
        SettingsScreen.setObjectName("SettingsScreen")
        SettingsScreen.resize(760, 580)
        self.centralwidget = QtWidgets.QWidget(SettingsScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(20, 20, 121, 51))
        self.button1.setObjectName("button1")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(20, 140, 121, 51))
        self.button3.setObjectName("button3")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(20, 80, 121, 51))
        self.button2.setObjectName("button2")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(20, 200, 121, 51))
        self.button4.setObjectName("button4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 141, 16))
        self.label.setObjectName("label")
        SettingsScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        SettingsScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsScreen)
        self.statusbar.setObjectName("statusbar")
        SettingsScreen.setStatusBar(self.statusbar)

        self.retranslateUi(SettingsScreen)
        QtCore.QMetaObject.connectSlotsByName(SettingsScreen)

    def retranslateUi(self, SettingsScreen):
        _translate = QtCore.QCoreApplication.translate
        SettingsScreen.setWindowTitle(_translate("SettingsScreen", "MainWindow"))
        self.button1.setText(_translate("SettingsScreen", "Tasks"))
        self.button3.setText(_translate("SettingsScreen", "Settings"))
        self.button2.setText(_translate("SettingsScreen", "Profile"))
        self.button4.setText(_translate("SettingsScreen", "Accounts"))
        self.label.setText(_translate("SettingsScreen", "Settings Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsScreen = QtWidgets.QMainWindow()
    ui = Ui_SettingsScreen()
    ui.setupUi(SettingsScreen)
    SettingsScreen.show()
    sys.exit(app.exec_())
