# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TasksScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TasksScreen(object):
    def setupUi(self, TasksScreen):
        TasksScreen.setObjectName("TasksScreen")
        TasksScreen.resize(760, 580)
        self.centralwidget = QtWidgets.QWidget(TasksScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(20, 20, 121, 51))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(20, 80, 121, 51))
        self.button2.setObjectName("button2")
        self.button3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3.setGeometry(QtCore.QRect(20, 140, 121, 51))
        self.button3.setObjectName("button3")
        self.button4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4.setGeometry(QtCore.QRect(20, 200, 121, 51))
        self.button4.setObjectName("button4")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(360, 110, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 10, 71, 16))
        self.label.setObjectName("label")
        TasksScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TasksScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        TasksScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TasksScreen)
        self.statusbar.setObjectName("statusbar")
        TasksScreen.setStatusBar(self.statusbar)

        self.retranslateUi(TasksScreen)
        QtCore.QMetaObject.connectSlotsByName(TasksScreen)

    def retranslateUi(self, TasksScreen):
        _translate = QtCore.QCoreApplication.translate
        TasksScreen.setWindowTitle(_translate("TasksScreen", "MainWindow"))
        self.button1.setText(_translate("TasksScreen", "Tasks"))
        self.button2.setText(_translate("TasksScreen", "Profile"))
        self.button3.setText(_translate("TasksScreen", "Settings"))
        self.button4.setText(_translate("TasksScreen", "Accounts"))
        self.label.setText(_translate("TasksScreen", "Tasks Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TasksScreen = QtWidgets.QMainWindow()
    ui = Ui_TasksScreen()
    ui.setupUi(TasksScreen)
    TasksScreen.show()
    sys.exit(app.exec_())
